### PR TITLE
Improve version compatibility

### PR DESCRIPTION
**Pull request by DrexHD**
In 23w03a the LVT of `initChannel` changed from `I, Lnet/minecraft/network/Connection;` to`Lio/netty/channel/ChannelPipeline;, I, Lnet/minecraft/network/Connection;`
This PR adds [MixinExtras](https://github.com/LlamaLad7/MixinExtras/) and uses it to access the required local variable, without caring about the rest of the LVT!

### CODE REVIEW

**Comment by Patbox** [comment]
Is MixinExtras really required? It it few times bigger than this lib by itself

**Comment by DrexHD** [comment]
I am not aware of any way, that keeps backwards compatibility with plain mixins. The alternative would be to make an extra version for 1.19.4, which would mean any mods using this library can't be backwards compatible...

**Comment by Patbox** [comment]
I will keep this open for now. Whatever it gets merged depends if fabric bundles mixin extras (which they mentioned as something they though of)

**Comment by Patbox** [comment]
Replaced the mixin with something better, to make it more universal

**Pull request closed without merging**
